name: xp3_archive
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  archive: ^3.3.5
  args: ^2.3.1
  progress_bar: ^1.0.0
